### ISSUE TITLE
When executing sudo ./startFabric.sh javascript An error occurred

### ISSUE THREAD

**Issue by antibodywzy** [Risvy/VSN-A-Hyperledger-Fabric-Project#1]
Hello author I am a computer student who is studying fabric. When I am running sudo ./startFabric.sh javascript in your tutorial
An error occurred at the time. I am trying to find out why. I want to ask if you have encountered this problem when you run it yourself? Can you provide me with a little help? Thank you!

![image](https://user-images.githubusercontent.com/40866484/116980439-cf9d6e00-acf8-11eb-9afc-65843b4ebe78.png)

**Comment by Risvy** [comment]
It seems your chaincode installation was failed because there is some sort of problem with docker.

### Possible Solution #1: 
Check if the docker is correctly installed. To see all the running containers in the docker engine:
```
docker ps
```
If the command is not successful, that means docker engine is not running. Try reinstalling docker.
### Possible Solution #2: 
If you have removed the docker images at some point, these problems may occur. I once faced a similar kind of problem with docker after killing the test network with these commands and the docker images were removed. Re-installing Hyperledger Fabric worked for me.

(These commands will stop the network and delete all the docker images. Do not run these command if you are not sure.)
```
docker rm -f $(docker ps -aq)
docker rmi -f $(docker images -q)

./startFabric.sh javascript
```

### Possible Solution #3: 
Assuming you installed the right version, did not move/delete any file and installed all the dependencies successfully, if the problem persists, try re-installing hyperledger fabric. Before that, rename the existing 'fabric-samples' folder to something else.  

PS: You can check these links:
https://github.com/hyperledger-labs/minifabric/issues/87
https://forum.linuxfoundation.org/discussion/857661/when-i-run-first-network-setup-shows-errors
https://github.com/docker/for-mac/issues/4955

**Comment by antibodywzy** [comment]
Thank you for your reply! I think this should be due to the failure of docker dns resolution after I used the virtual machine and vpn. I used Amazon's cloud server, and another problem occurred. I'm sure this is not caused by my local machine. Have you ever encountered such a situation?
![image](https://user-images.githubusercontent.com/40866484/117028947-c4fecb00-ad30-11eb-87a6-4b90889100e2.png)

**Comment by Risvy** [comment]
A discussion related to your query can be found here:
https://stackoverflow.com/questions/62445415/error-deploying-fabric-test-network-fabcar-chaincode

Thanks.

**Comment by antibodywzy** [comment]
Thank you so much, after hard work I finally reached the last step. But it has another problem, and I am still trying to solve it. Have you encountered a similar problem? Thank you!
![image](https://user-images.githubusercontent.com/40866484/117047342-575c9a00-ad44-11eb-96a5-f10ce034695d.png)
